version: '3.9'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - ./app:/app  # Mount local `app` folder into the container for live changes during development
    restart: always