[tool.poetry]
name = "pyfindings"
version = "0.1.0"
description = ""
authors = ["Aidar Darmesh <darmesh.aidar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.10.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
